import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import Footer_component from "../../components/footer/footer";
import Header_Component from "../../components/header/header";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      //className={inter.className}
      >
        <Header_Component/>
        <hr/>
        {children}
        <hr/>
        <Footer_component/>
      </body>
    </html>
  );
}
